import React, { useRef } from 'react';
import { Download, Share2 } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

export default function WrappedCard({ bpm, hrv, stress, burnout, onClose }) {
  const { t } = useLanguage();
  const canvasRef = useRef(null);

  const getBurnoutLevel = (index) => {
    if (index > 70) return t('fatigueHigh');
    return t('fatigueNormal');
  };

  const drawCard = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    
    // Luxurious Deep Background (Midnight Blue to Charcoal)
    const bgGradient = ctx.createRadialGradient(canvas.width/2, canvas.height/3, 50, canvas.width/2, canvas.height/2, 800);
    bgGradient.addColorStop(0, '#0f172a'); // slate-900
    bgGradient.addColorStop(1, '#020617'); // slate-950
    ctx.fillStyle = bgGradient;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Premium Gold Accents
    ctx.strokeStyle = 'rgba(212, 175, 55, 0.3)'; // Gold border
    ctx.lineWidth = 2;
    ctx.strokeRect(30, 30, canvas.width - 60, canvas.height - 60);
    ctx.lineWidth = 1;
    ctx.strokeRect(36, 36, canvas.width - 72, canvas.height - 72);

    // Title
    ctx.fillStyle = '#ffffff';
    ctx.font = '400 28px Georgia, serif';
    ctx.textAlign = 'center';
    ctx.fillText('B I O - M I R R O R', canvas.width / 2, 90);
    
    ctx.fillStyle = '#d4af37'; // Gold
    ctx.font = 'italic 16px Georgia, serif';
    ctx.fillText('Personal Wellness Report', canvas.width / 2, 120);

    // Divider
    ctx.beginPath();
    ctx.moveTo(canvas.width/2 - 100, 150);
    ctx.lineTo(canvas.width/2 + 100, 150);
    ctx.strokeStyle = 'rgba(212, 175, 55, 0.5)';
    ctx.stroke();

    // Vitals Blocks
    const drawVital = (label, value, unit, y, color) => {
       ctx.fillStyle = color;
       ctx.font = '600 52px sans-serif';
       ctx.fillText(value, canvas.width / 2, y);
       ctx.fillStyle = '#94a3b8'; // slate-400
       ctx.font = '400 14px sans-serif';
       ctx.fillText(`${label} (${unit})`, canvas.width / 2, y + 25);
    };

    drawVital('HEART RATE', bpm, 'BPM', 240, '#f8fafc');
    drawVital('HEART RATE VARIABILITY', hrv, 'ms', 330, '#f8fafc');
    drawVital('STRESS LEVEL', `${stress}`, '%', 420, stress > 65 ? '#fca5a5' : '#f8fafc');
    drawVital('BURNOUT INDEX', `${burnout}`, '%', 510, burnout > 70 ? '#fca5a5' : '#f8fafc');

    // Recommendation Section
    ctx.fillStyle = '#d4af37';
    ctx.font = '600 16px sans-serif';
    ctx.fillText('CLINICAL INSIGHT', canvas.width / 2, 600);

    // Get Medical Advice
    let rec = t('recOptimal');
    if (stress > 65 || burnout > 70) rec = t('recStress');
    else if (hrv < 25) rec = t('recLowHrv');
    else if (bpm < 60 && hrv > 60) rec = t('recAthletic');

    // Wrap Text Logic
    ctx.fillStyle = '#e2e8f0';
    ctx.font = 'italic 400 16px Georgia, serif';
    const words = rec.split(' ');
    let line = '';
    let y = 640;
    const maxWidth = canvas.width - 120;
    
    for(let n = 0; n < words.length; n++) {
      let testLine = line + words[n] + ' ';
      let metrics = ctx.measureText(testLine);
      let testWidth = metrics.width;
      if (testWidth > maxWidth && n > 0) {
        ctx.fillText(line, canvas.width / 2, y);
        line = words[n] + ' ';
        y += 26;
      }
      else {
        line = testLine;
      }
    }
    ctx.fillText(line, canvas.width / 2, y);

    // Date & Signature
    ctx.fillStyle = 'rgba(255,255,255,0.2)';
    ctx.font = '10px sans-serif';
    ctx.fillText(`Generated by Bio-Mirror Edge AI on ${new Date().toLocaleDateString()}`, canvas.width / 2, 750);
  };

  const handleDownload = () => {
    drawCard();
    const link = document.createElement('a');
    link.download = `bio-mirror-wrapped-${Date.now()}.png`;
    link.href = canvasRef.current.toDataURL('image/png');
    link.click();
  };

  // Auto-draw when component mounts
  React.useEffect(() => {
    drawCard();
  }, [bpm, hrv, stress, burnout]);

  return (
    <div className="w-full flex flex-col items-center mt-6">
      <div className="hidden">
        <canvas ref={canvasRef} width="600" height="800"></canvas>
      </div>
      <button 
        onClick={handleDownload}
        className="btn-cyber w-full py-4 text-[10px] sm:text-xs flex items-center justify-center space-x-2 border-cyber-purple text-cyber-purple hover:bg-cyber-purple/20 hover:shadow-[0_0_15px_#b800ff]"
      >
        <Download size={16} />
        <span>{t('downloadReport')}</span>
      </button>
    </div>
  );
}
