import React, { useRef } from 'react';
import { Download, Share2 } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

export default function WrappedCard({ bpm, hrv, stress, burnout, onClose }) {
  const { t } = useLanguage();
  const canvasRef = useRef(null);

  const getBurnoutLevel = (index) => {
    if (index > 70) return t('fatigueHigh');
    return t('fatigueNormal');
  };

  const drawCard = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    
    // Draw Background
    ctx.fillStyle = '#07090f';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Draw Cyberpunk Grid
    ctx.strokeStyle = 'rgba(0, 240, 255, 0.1)';
    ctx.lineWidth = 1;
    for(let i=0; i<canvas.width; i+=40) {
      ctx.beginPath(); ctx.moveTo(i, 0); ctx.lineTo(i, canvas.height); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(0, i); ctx.lineTo(canvas.width, i); ctx.stroke();
    }

    // Border
    ctx.strokeStyle = '#00f0ff';
    ctx.lineWidth = 4;
    ctx.strokeRect(20, 20, canvas.width - 40, canvas.height - 40);

    // Title
    ctx.fillStyle = '#00f0ff';
    ctx.font = 'bold 36px monospace';
    ctx.textAlign = 'center';
    ctx.fillText('BIO-MIRROR WRAPPED', canvas.width / 2, 80);

    // Vitals Blocks
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 48px sans-serif';
    ctx.fillText(`${bpm} BPM`, canvas.width / 2, 200);
    ctx.fillStyle = '#888888';
    ctx.font = '16px monospace';
    ctx.fillText('AVERAGE HEART RATE', canvas.width / 2, 230);

    ctx.fillStyle = '#b800ff';
    ctx.font = 'bold 48px sans-serif';
    ctx.fillText(`${hrv} ms`, canvas.width / 2, 330);
    ctx.fillStyle = '#888888';
    ctx.font = '16px monospace';
    ctx.fillText('HEART RATE VARIABILITY', canvas.width / 2, 360);

    // Stress & Burnout
    const stressColor = stress > 65 ? '#ff003c' : '#00ff41';
    ctx.fillStyle = stressColor;
    ctx.font = 'bold 32px sans-serif';
    ctx.fillText(`STRESS: ${stress}%`, canvas.width / 2, 450);

    const burnoutColor = burnout > 70 ? '#ff003c' : '#00f0ff';
    ctx.fillStyle = burnoutColor;
    ctx.font = 'bold 32px sans-serif';
    ctx.fillText(`BURNOUT: ${burnout}%`, canvas.width / 2, 530);

    // Watermark
    ctx.fillStyle = 'rgba(255,255,255,0.3)';
    ctx.font = '12px monospace';
    ctx.fillText('GENERATED BY BIO-MIRROR EDGE', canvas.width / 2, 750);
  };

  const handleDownload = () => {
    drawCard();
    const link = document.createElement('a');
    link.download = `bio-mirror-wrapped-${Date.now()}.png`;
    link.href = canvasRef.current.toDataURL('image/png');
    link.click();
  };

  // Auto-draw when component mounts
  React.useEffect(() => {
    drawCard();
  }, [bpm, hrv, stress, burnout]);

  return (
    <div className="w-full flex flex-col items-center mt-6">
      <div className="hidden">
        <canvas ref={canvasRef} width="600" height="800"></canvas>
      </div>
      <button 
        onClick={handleDownload}
        className="btn-cyber w-full py-4 text-[10px] sm:text-xs flex items-center justify-center space-x-2 border-cyber-purple text-cyber-purple hover:bg-cyber-purple/20 hover:shadow-[0_0_15px_#b800ff]"
      >
        <Download size={16} />
        <span>{t('downloadReport')}</span>
      </button>
    </div>
  );
}
