import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  en: {
    title: "Bio-Mirror",
    subtitle: "EDGE COMPUTING VITAL SIGNS",
    install: "INSTALL TO YOUR DEVICE",
    history: "HISTORY",
    systemStandby: "SYSTEM STANDBY",
    initScanner: "INITIALIZE SCANNER",
    awaiting: "AWAITING BIOMETRICS...",
    scanning: "SCANNING... PLEASE HOLD STILL",
    completed: "SCAN COMPLETED",
    heartRate: "Heart Rate",
    heartRateVar: "Heart Rate Var",
    stressLevel: "Stress Level",
    recorded: "RECORDED",
    optimal: "OPTIMAL",
    high: "HIGH",
    normal: "NORMAL",
    low: "LOW",
    unusual: "UNUSUAL",
    analyzing: "ANALYZING...",
    standby: "STANDBY",
    normalRange: "Normal Range",
    digitalTwin: "Digital Twin",
    ecgScanner: "ECG Scanner (rPPG)",
    highStressTitle: "ELEVATED STRESS DETECTED",
    highStressMsg: "Your heart rate and stress levels are higher than normal. Please take a few deep breaths and rest for 5 minutes.",
    athleticTitle: "ATHLETIC RESTING STATE",
    athleticMsg: "Excellent heart efficiency! Your body is highly relaxed and showing great cardiovascular recovery.",
    lowRecoveryTitle: "LOW RECOVERY DETECTED",
    lowRecoveryMsg: "Your HRV is quite low, indicating physical fatigue or mental strain. Ensure you get adequate sleep.",
    optimalTitle: "OPTIMAL HEALTH",
    optimalMsg: "All vital signs are perfectly within healthy resting limits. Keep up the good work!",
    moderateTitle: "MODERATE STATE",
    moderateMsg: "Your vitals are stable. Stay hydrated and take short breaks if you are working.",
    recStress: "Immediate rest required. Practice deep breathing using the Healing Mode. Hydrate and take a 15-min nap.",
    recLowHrv: "Low recovery detected. Avoid caffeine and intense workouts today. Prioritize 8 hours of sleep.",
    recAthletic: "Peak athletic condition! Your cardiovascular system is operating at optimal efficiency.",
    recOptimal: "Optimal vitals. Maintain your current routine. Stay hydrated and take short breaks.",
    initializeInstruction: "Click below to initialize the Edge AI scanner and grant camera access.",
    loadingEngine: "LOADING AI ENGINE...",
    extractingVitals: "EXTRACTING VITALS",
    scanComplete: "SCAN COMPLETE",
    vitalsRecorded: "Vital signs successfully recorded. Camera hardware disabled.",
    startNewScan: "START NEW SCAN",
    vitalsHistory: "Vitals History",
    audio: "AUDIO",
    muted: "MUTED",
    privateBadge: "100% PRIVATE",
    privateTooltip: "All AI processing runs on your device locally. No video is ever sent to servers.",
    fpsTooltip: "Frames Per Second. Indicates AI speed & performance.",
    instTitle: "For Maximum AI Accuracy",
    inst1: "Ensure good lighting on your face",
    inst2: "Keep your head completely still",
    inst3: "Remove glasses or face masks",
    alertMotion: "MOTION DETECTED - PLEASE HOLD STILL",
    alertLowLight: "LOW LIGHT - PLEASE FACE A LIGHT SOURCE",
    twinInfoTitle: "What is the Digital Twin?",
    twinInfoDesc: "It maps 468 facial points in 3D space to track micro-movements and blood flow regions. Color reflects your live stress state (Cyan = Calm, Red = Stressed).",
    twinNodes: "NODES: 468 ACTIVE",
    twinDepth: "Z-DEPTH: TRACKING",
    cancelScan: "ABORT SCAN",
    burnoutIndex: "Burnout Index",
    healingMode: "BIO-HEALER PROTOCOL",
    inhale: "INHALE",
    hold: "HOLD",
    exhale: "EXHALE",
    downloadReport: "DOWNLOAD WRAPPED",
    fatigueHigh: "EXTREME FATIGUE",
    fatigueNormal: "WELL RESTED",
    quote1: "Focus only on your breath...",
    quote2: "Let go of the past...",
    quote3: "Be in the present moment.",
    quote4: "Your mind is like the sky...",
    quote5: "Troubles are passing clouds.",
    ready: "GET READY",
    readyPrompt: "Sit comfortably and relax your shoulders...",
    startHealing: "START SESSION",
    exportCsv: "EXPORT CSV",
    installAppTitle: "Install App",
    installAppSubtitle: "BIO-MIRROR EDGE AI",
    noApkNeeded: "No APK needed. Install directly as a native app:",
    androidTitle: "Android (Chrome)",
    androidDesc1: "Tap ",
    androidDesc2: " menu (top right) → select ",
    androidDesc3: "\"Add to Home screen\"",
    iosTitle: "iOS (Safari)",
    iosDesc1: "Tap ",
    iosDesc2: " button at the bottom → select ",
    iosDesc3: "\"Add to Home Screen\"",
    desktopTitle: "Desktop (Chrome / Edge)",
    desktopDesc1: "Click the ",
    desktopDesc2: " in the URL bar (next to the bookmark star)",
    closeBtn: "CLOSE"
  },
  si: {
    title: "බයෝ-මිරර්",
    subtitle: "එජ් AI සෞඛ්‍ය පරීක්‍ෂකය",
    install: "දුරකථනයට ස්ථාපනය කරන්න",
    history: "ඉතිහාසය",
    systemStandby: "පද්ධතිය සූදානම්",
    initScanner: "පරීක්‍ෂාව ආරම්භ කරන්න",
    awaiting: "මුහුණ හඳුනාගනිමින්...",
    scanning: "පරීක්‍ෂා කරමින්... නිශ්චලව සිටින්න",
    completed: "පරීක්‍ෂාව අවසන්",
    heartRate: "හෘද ස්පන්දනය",
    heartRateVar: "HRV (හෘද ස්පන්දන විචල්‍යය)",
    stressLevel: "ආතති මට්ටම",
    recorded: "සටහන් විය",
    optimal: "ප්‍රශස්තයි",
    high: "ඉහළයි",
    normal: "සාමාන්‍යයි",
    low: "අවමයි",
    unusual: "අසාමාන්‍යයි",
    analyzing: "විශ්ලේෂණය කරමින්...",
    standby: "සූදානම්",
    normalRange: "සාමාන්‍ය පරාසය",
    digitalTwin: "ත්‍රිමාණ මුහුණ",
    ecgScanner: "ECG පරීක්‍ෂකය (rPPG)",
    highStressTitle: "අධික ආතතියක් හඳුනාගැනුණි",
    highStressMsg: "ඔබගේ හෘද ස්පන්දනය සහ ආතතිය ඉහළ මට්ටමක පවතී. කරුණාකර ගැඹුරින් හුස්ම ගෙන විනාඩි 5ක් පමණ විවේක ගන්න.",
    athleticTitle: "විශිෂ්ට සෞඛ්‍ය තත්ත්වයක්",
    athleticMsg: "ඔබගේ හෘදයේ ක්‍රියාකාරිත්වය ඉතා විශිෂ්ටයි! ශරීරය හොඳින් විවේකීව පවතී.",
    lowRecoveryTitle: "අඩු විවේක මට්ටමක්",
    lowRecoveryMsg: "ඔබගේ HRV අගය අඩුයි. මෙයින් කායික හෝ මානසික මහන්සියක් පෙන්නුම් කරයි. හොඳින් නිදාගන්න.",
    optimalTitle: "ප්‍රශස්ත සෞඛ්‍යයක්",
    optimalMsg: "ඔබගේ සියලුම සෞඛ්‍ය දත්ත සාමාන්‍ය මට්ටමේ පවතී. ඉතා හොඳයි!",
    moderateTitle: "සාමාන්‍ය තත්ත්වයක්",
    moderateMsg: "දත්ත සාමාන්‍යයි. ජලය පානය කර අවශ්‍ය නම් සුළු විවේකයක් ගන්න.",
    recStress: "ඔබට විවේකය අත්‍යවශ්‍යයි! ගැඹුරු හුස්ම ගැනීමේ ව්‍යායාමයක් කරන්න. ජලය පානය කර විනාඩි 15ක පමණ නින්දක් ලබාගන්න.",
    recLowHrv: "ශරීරය වෙහෙසට පත්වී ඇත. කෝපි බීම සහ ව්‍යායාම කිරීම අදට නවත්වන්න. පැය 8ක නින්දක් අනිවාර්යයෙන් ලබාගන්න.",
    recAthletic: "ඉතාමත් නිරෝගී තත්ත්වයක්! ඔබගේ හෘද ක්‍රියාකාරිත්වය ක්‍රීඩකයෙකුගේ මෙන් ඉතා ඉහළ මට්ටමක පවතී.",
    recOptimal: "ඉතා හොඳ සෞඛ්‍ය මට්ටමක්! ඔබගේ දෛනික පුරුදු මේ ආකාරයෙන්ම පවත්වා ගන්න. සුළු විවේක ලබාගැනීමට අමතක නොකරන්න.",
    initializeInstruction: "කරුණාකර කැමරාවට අවසර ලබා දීමට පහත බොත්තම ඔබන්න.",
    loadingEngine: "AI පද්ධතිය සකස් වෙමින් පවතී...",
    extractingVitals: "දත්ත ලබා ගනිමින් පවතී...",
    scanComplete: "පරීක්‍ෂාව සම්පූර්ණයි",
    vitalsRecorded: "දත්ත සටහන් විය. කැමරාව සාර්ථකව විසන්ධි කරන ලදී.",
    startNewScan: "නව පරීක්‍ෂාවක් ආරම්භ කරන්න",
    vitalsHistory: "සෞඛ්‍ය දත්ත ඉතිහාසය",
    audio: "ශබ්දය",
    muted: "නිහඬයි",
    privateBadge: "100% පුද්ගලිකයි",
    privateTooltip: "සියලුම දත්ත ඔබගේ දුරකථනය තුළ පමණක් විශ්ලේෂණය වේ. කිසිදු වීඩියෝවක් අන්තර්ජාලයට යවන්නේ නැත.",
    fpsTooltip: "AI පද්ධතියේ වේගය සහ ක්‍රියාකාරීත්වය පෙන්වයි.",
    instTitle: "නිවැරදි දත්ත ලබාගැනීම සඳහා",
    inst1: "මුහුණට හොඳ ආලෝකයක් ලබාදෙන්න",
    inst2: "කැමරාව දෙස කෙළින් බලා නිශ්චලව සිටින්න",
    inst3: "කණ්ණාඩි හෝ මුහුණු ආවරණ ඉවත් කරන්න",
    alertMotion: "හිස චලනය වේ! කරුණාකර නිශ්චලව සිටින්න",
    alertLowLight: "ආලෝකය මදි! ආලෝකය දෙසට හැරෙන්න",
    twinInfoTitle: "ත්‍රිමාණ මුහුණ යනු කුමක්ද?",
    twinInfoDesc: "මෙයින් මුහුණේ ලක්‍ෂ්‍ය 468ක් ත්‍රිමාණව සිතියම් ගත කර රුධිර ගමනාගමනය සහ සියුම් චලනයන් විශ්ලේෂණය කරයි. වර්ණයෙන් ආතති මට්ටම පෙන්වයි.",
    twinNodes: "ලක්‍ෂ්‍ය 468ක් සක්‍රීයයි",
    twinDepth: "ත්‍රිමාණ දුර මැනීම: සක්‍රීයයි",
    cancelScan: "පරීක්‍ෂාව නවත්වන්න",
    burnoutIndex: "මනෝකායික වෙහෙස (Burnout)",
    healingMode: "සුව කිරීමේ පද්ධතිය",
    inhale: "හුස්ම ගන්න",
    hold: "රඳවාගන්න",
    exhale: "පිට කරන්න",
    downloadReport: "වාර්තාව බාගත කරන්න",
    fatigueHigh: "අධික වෙහෙසයි",
    fatigueNormal: "හොඳින් විවේකීව සිටී",
    quote1: "හුස්ම කෙරෙහි පමණක් අවධානය යොමු කරන්න...",
    quote2: "අතීතය අතහරින්න...",
    quote3: "මේ මොහොතේ ජීවත් වෙන්න.",
    quote4: "ඔබේ සිත අහසක් වැනිය...",
    quote5: "ප්‍රශ්න යනු එහි පාවෙන වලාකුළු පමණි.",
    ready: "සූදානම් වන්න",
    readyPrompt: "සුවපහසුව වාඩි වී ඔබේ දෑස් සහ උරහිස් සැහැල්ලු කරගන්න...",
    startHealing: "සුවපත් වීම ආරම්භ කරන්න",
    exportCsv: "දත්ත බාගත කරන්න (CSV)",
    installAppTitle: "App එක ස්ථාපනය කරගන්න",
    installAppSubtitle: "BIO-MIRROR EDGE AI",
    noApkNeeded: "APK අවශ්‍ය නැත. කෙලින්ම App එකක් ලෙස ස්ථාපනය කරගන්න:",
    androidTitle: "Android (Chrome)",
    androidDesc1: "ඔබන්න ",
    androidDesc2: " මෙනුව (දකුණු පස ඉහළ) → තෝරන්න ",
    androidDesc3: "\"Add to Home screen\"",
    iosTitle: "iOS (Safari)",
    iosDesc1: "ඔබන්න ",
    iosDesc2: " බොත්තම (පහළ) → තෝරන්න ",
    iosDesc3: "\"Add to Home Screen\"",
    desktopTitle: "Desktop (Chrome / Edge)",
    desktopDesc1: "ක්ලික් කරන්න ",
    desktopDesc2: " URL තීරුවේ (තරු ලකුණ අසල)",
    closeBtn: "වසා දමන්න"
  },
  ta: {
    title: "பயோ-மிரர்",
    subtitle: "எட்ஜ் ஏஐ சுகாதார ஸ்கேனர்",
    install: "சாதனத்தில் நிறுவவும்",
    history: "வரலாறு",
    systemStandby: "கணினி தயாராக உள்ளது",
    initScanner: "ஸ்கேனரைத் தொடங்கு",
    awaiting: "முகத்தை அடையாளம் காணப்படுகிறது...",
    scanning: "ஸ்கேன் செய்யப்படுகிறது... அசையாமல் இருங்கள்",
    completed: "ஸ்கேன் முடிந்தது",
    heartRate: "இதய துடிப்பு",
    heartRateVar: "இதய துடிப்பு மாறுபாடு",
    stressLevel: "மன அழுத்தம்",
    recorded: "பதிவுசெய்யப்பட்டது",
    optimal: "உகந்த",
    high: "உயர்ந்த",
    normal: "சாதாரண",
    low: "குறைவு",
    unusual: "வழக்கத்திற்கு மாறான",
    analyzing: "பகுப்பாய்கிறது...",
    standby: "தயார்",
    normalRange: "சாதாரண வரம்பு",
    digitalTwin: "3D டிஜிட்டல் ட்வின்",
    ecgScanner: "ECG ஸ்கேனர் (rPPG)",
    highStressTitle: "அதிக மன அழுத்தம்",
    highStressMsg: "உங்கள் இதய துடிப்பு மற்றும் மன அழுத்தம் அதிகமாக உள்ளது. ஆழமாக மூச்சு விட்டு 5 நிமிடங்கள் ஓய்வெடுக்கவும்.",
    athleticTitle: "சிறந்த உடல்நலம்",
    athleticMsg: "உங்கள் இதய செயல்பாடு மிகவும் சிறப்பானது! உடல் நன்கு ஓய்வெடுக்கிறது.",
    lowRecoveryTitle: "குறைந்த மீட்பு நிலை",
    lowRecoveryMsg: "உங்கள் HRV மிகவும் குறைவாக உள்ளது. இது உடல் சோர்வைக் குறிக்கிறது. நன்கு உறங்கவும்.",
    optimalTitle: "உகந்த ஆரோக்கியம்",
    optimalMsg: "அனைத்து முக்கிய அறிகுறிகளும் ஆரோக்கியமான வரம்பிற்குள் உள்ளன. நன்று!",
    moderateTitle: "மிதமான நிலை",
    moderateMsg: "உங்கள் உடல்நிலை சீராக உள்ளது. தண்ணீர் குடித்து சிறிது ஓய்வெடுக்கவும்.",
    recStress: "உடனடி ஓய்வு தேவை. குணப்படுத்தும் முறையைப் பயன்படுத்தி ஆழ்ந்த மூச்சுப் பயிற்சி செய்யவும். தண்ணீர் குடித்து 15 நிமிடம் தூங்கவும்.",
    recLowHrv: "குறைந்த மீட்பு கண்டறியப்பட்டது. காபி மற்றும் கடுமையான உடற்பயிற்சிகளை தவிர்க்கவும். 8 மணி நேர தூக்கத்திற்கு முன்னுரிமை கொடுங்கள்.",
    recAthletic: "சிறந்த ஆரோக்கிய நிலை! உங்கள் இதய அமைப்பு மிகச்சிறப்பாக செயல்படுகிறது.",
    recOptimal: "உகந்த ஆரோக்கியம். இதே நிலையை தொடரவும். தண்ணீர் குடித்து சிறிது ஓய்வெடுக்கவும்.",
    initializeInstruction: "கேமரா அணுகலை வழங்க கீழே உள்ள பொத்தானைக் கிளிக் செய்யவும்.",
    loadingEngine: "AI கணினி தயாராகிறது...",
    extractingVitals: "தரவு பிரித்தெடுக்கப்படுகிறது",
    scanComplete: "ஸ்கேன் முடிந்தது",
    vitalsRecorded: "தரவு பதிவு செய்யப்பட்டது. கேமரா அணைக்கப்பட்டது.",
    startNewScan: "புதிய ஸ்கேன் தொடங்கு",
    vitalsHistory: "சுகாதார வரலாறு",
    audio: "ஆடியோ",
    muted: "முடக்கப்பட்டது",
    privateBadge: "100% தனிப்பட்ட",
    privateTooltip: "அனைத்து AI செயலாக்கங்களும் உங்கள் சாதனத்தில் மட்டுமே நடக்கும். வீடியோ எங்கும் அனுப்பப்படாது.",
    fpsTooltip: "விநாடிக்கு சட்டங்கள். AI வேகம் மற்றும் செயல்திறனைக் குறிக்கிறது.",
    instTitle: "துல்லியமான முடிவுகளுக்கு",
    inst1: "முகத்தில் நல்ல வெளிச்சம் இருப்பதை உறுதி செய்யவும்",
    inst2: "தலையை அசைக்காமல் நேராக பார்க்கவும்",
    inst3: "கண்ணாடி அல்லது முகமூடிகளை அகற்றவும்",
    alertMotion: "இயக்கம் கண்டறியப்பட்டது! அசையாமல் இருங்கள்",
    alertLowLight: "குறைந்த வெளிச்சம்! வெளிச்சத்தை நோக்கி திரும்பவும்",
    twinInfoTitle: "டிஜிட்டல் ட்வின் என்றால் என்ன?",
    twinInfoDesc: "இது 468 புள்ளிகளை 3D-யில் வரைபடமாக்குகிறது. சிறிய அசைவுகள் மற்றும் இரத்த ஓட்டத்தை பகுப்பாய்வு செய்கிறது. நிறம் மன அழுத்தத்தைக் குறிக்கிறது.",
    twinNodes: "புள்ளிகள் 468: செயலில்",
    twinDepth: "3D ஆழம்: கண்காணிக்கப்படுகிறது",
    cancelScan: "ரத்துசெய்",
    burnoutIndex: "சோர்வு நிலை",
    healingMode: "குணப்படுத்தும் முறை",
    inhale: "மூச்சை உள்ளிழுங்கள்",
    hold: "பிடித்துக்கொள்ளுங்கள்",
    exhale: "மூச்சை விடுங்கள்",
    downloadReport: "அறிக்கையை பதிவிறக்கவும்",
    fatigueHigh: "அதிக சோர்வு",
    fatigueNormal: "நன்கு ஓய்வெடுத்துள்ளார்",
    quote1: "உங்கள் மூச்சில் மட்டும் கவனம் செலுத்துங்கள்...",
    quote2: "கடந்த காலத்தை விட்டுவிடுங்கள்...",
    quote3: "நிகழ்காலத்தில் வாழுங்கள்.",
    quote4: "உங்கள் மனம் வானம் போன்றது...",
    quote5: "பிரச்சனைகள் கடந்து செல்லும் மேகங்கள்.",
    ready: "தயாராகுங்கள்",
    readyPrompt: "வசதியாக அமர்ந்து உங்கள் உடலை தளர்த்திக் கொள்ளுங்கள்...",
    startHealing: "தொடங்கவும்",
    exportCsv: "பதிவிறக்க (CSV)",
    installAppTitle: "செயலியை நிறுவவும்",
    installAppSubtitle: "BIO-MIRROR EDGE AI",
    noApkNeeded: "APK தேவையில்லை. நேரடியாக செயலியாக நிறுவவும்:",
    androidTitle: "Android (Chrome)",
    androidDesc1: "அழுத்தவும் ",
    androidDesc2: " மெனு (மேல் வலது) → தேர்ந்தெடுக்கவும் ",
    androidDesc3: "\"Add to Home screen\"",
    iosTitle: "iOS (Safari)",
    iosDesc1: "அழுத்தவும் ",
    iosDesc2: " பொத்தான் (கீழே) → தேர்ந்தெடுக்கவும் ",
    iosDesc3: "\"Add to Home Screen\"",
    desktopTitle: "Desktop (Chrome / Edge)",
    desktopDesc1: "கிளிக் செய்யவும் ",
    desktopDesc2: " URL பட்டியில் (நட்சத்திரக் குறிக்கு அருகில்)",
    closeBtn: "மூடவும்"
  }
};
const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('bio_mirror_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('bio_mirror_lang', lang);
  }, [lang]);

  const t = (key) => translations[lang][key] || translations['en'][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
